export const CONNECTION_REQUEST = 'CONNECTION_REQUEST'
export const CONNECTION_SUCCESS = 'CONNECTION_SUCCESS'
export const CONNECTION_FAILED = 'CONNECTION_FAILED'
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT'

export const USER_SIGNUP_REQUEST ='USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESS ='USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAILED ='USER_SIGNUP_FAILED'

export const USER_SIGNIN_REQUEST ='USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS ='USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_FAILED ='USER_SIGNIN_FAILED'

export const GET_USER_REQUEST ='GET_USER_REQUEST'
export const GET_USER_SUCCESS ='GET_USER_SUCCESS'
export const GET_USER_FAILED ='GET_USER_FAILED'

export const GET_ALL_PLANS_REQUEST ='GET_ALL_PLANS_REQUEST'
export const GET_ALL_PLANS_SUCCESS ='GET_ALL_PLANS_SUCCESS'
export const GET_ALL_PLANS_FAILED ='GET_ALL_PLANS_FAILED'

export const CREATE_SUB_REQUEST ='CREATE_SUB_REQUEST'
export const CREATE_SUB_SUCCESS ='CREATE_SUB_SUCCESS'
export const CREATE_SUB_FAILED ='CREATE_SUB_FAILED'


export const DELETE_SUB_SUCCESS ='DELETE_SUB_SUCCESS'
export const DELETE_SUB_FAILED ='DELETE_SUB_FAILED'

export const GET_SUB_BY_ID_REQUEST ='GET_SUB_BY_ID_REQUEST'
export const GET_SUB_BY_ID_SUCCESS ='GET_SUB_BY_ID_SUCCESS'
export const GET_SUB_BY_ID_FAILED ='GET_SUB_BY_ID_FAILED'

export const SUBSCRIPTION_SUCCESS ='SUBSCRIPTION_SUCCESS'
export const SUBSCRIPTION_FAILED ='SUBSCRIPTION_FAILED'

export const USER_SUBCRIPTION ='USER_SUBCRIPTION'

export const USER_LOGOUT ='USER_LOGOUT'